<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>mOCR</title>
        
        <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">
        <link rel="stylesheet" href="https://bootswatch.com/4/materia/bootstrap.min.css">
        <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">
        <!--        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/fabric.js/2.2.0/fabric.min.js"></script>

        <style>
            /* For Snackbar */
            #snackbar {
                visibility: hidden;
                min-width: 250px;
                margin-left: -125px;
                background-color: #222222;
                color: #ffffff;
                text-align: center;
                border-radius: 2.25rem;
                padding: 16px;
                position: fixed;
                z-index: 1;
                left: 50%;
                bottom: 30px;
                font-size: 17px;
            }

            #snackbar.show {
                visibility: visible;
                -webkit-animation: fadein 0.5s, fadeout 0.5s 2.5s;
                animation: fadein 0.5s, fadeout 0.5s 2.5s;
            }

            @-webkit-keyframes fadein {
                from {bottom: 0; opacity: 0;}
                to {bottom: 30px; opacity: 1;}
            }

            @keyframes fadein {
                from {bottom: 0; opacity: 0;}
                to {bottom: 30px; opacity: 1;}
            }

            @-webkit-keyframes fadeout {
                from {bottom: 30px; opacity: 1;}
                to {bottom: 0; opacity: 0;}
            }

            @keyframes fadeout {
                from {bottom: 30px; opacity: 1;}
                to {bottom: 0; opacity: 0;}
            }
            /* Snackbar end */
            body {
                margin: 0 0;
                padding: 0;
                width: 100%;
                text-align: center;
                font-size: 1.3rem;
            }
            #canvas {
                border: 2px solid black;
                border-radius: 3px;
                margin: auto;
            }
            .canvas-container {
                margin: auto;
            }
            .icon-container {
                display: flex;
                width: 300px;
                margin: auto;
            }
            .icon-container > div {
                flex: 1;
                padding: 19px 0;
                background-color: #ffffffff;
            }
            .icon-container > div:hover {
                background-color: #e5e5e5;
                cursor: pointer;
            }
            .icon-container > div > div {
                font-size: 0.5rem;
            }
            .splash {
                padding: 6em 0 3em;
                background-color: #2196F3;
                color: #ffffff;
                text-align: center;
            }

            .handwr {
                font-family: 'Gloria Hallelujah', cursive;
            }
            .heading {
                font-size: 30vw;
            }
            .subheading {
                font-size: 2rem;
                color: #ffffff80;
            }
            .header-desc {
                font-size: 1.5rem;
            }
            .header-desc > a {
                color: #ffffff;
            }
            .row {
                margin:0;
            }
            #data_contrib {
                padding-top: 20px;
                font-size: 2rem;
                font-weight: bold;
            }
            #charSelect {
                width: auto;
                display: inline;
                min-width: 3rem;
                font-size: 1.5rem;
                height: 4rem;
            }
            @media screen and (min-width: 768px) {
                .heading {
                    font-size: 8rem;
                }
            }
            @media screen and (max-width: 768px) {
                .md-only {
                    display: none;
                }
            }
        </style>
        
    </head>
    <body>
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary navbar-transparent">
            <div class="container">
                <a class="navbar-brand handwr" href="#">mOCR</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Get Dataset</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="mailto:admin@mocr.ml" target="_top">Contact Us</a>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                    </form>
                </div>
                <ul class="navbar-nav flex-row ml-md-auto d-none d-lg-flex">
                    <li class="nav-item">
                        <a class="nav-link p-2" href="https://github.com/" target="_blank">
                            <i class="fab fa-github"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="splash" style="background-position: 0px 0px;">
            <div class="container">

                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="heading handwr">mOCR</h1>
                        <div class="subheading">Malayalam OCR</div>
                        <p class="header-desc"><span class="handwr">mOCR</span> is an open-source Optical Character Recognition for Malayalam language.</p>
                        <p class="header-desc"> It is a work in progress. For now, <a href="#data_contrib">contribute</a> to the data collection.</p>
                        <p  class="header-desc">
                            <a href="#data_contrib"><button type="button" class="btn btn-secondary">Take me there</button></a>
                        </p>

                    </div>
                </div>

            </div>
        </div>
        <div class="row justify-content-center">
            <div class="container">
                <div id="data_contrib">Contribute to data collection</div>
                <div class="md-only text-danger">Use a touchscreen device or a stylus for better experience</div>
                <div>Write the current character in the canvas below</div>
                <div class="form-group">
                    <label for="charSelect">Current character</label>
                    <select class="form-control" id="charSelect">
                        <?php foreach ($chars as $key => $value): ?>
                        <option value= <?=$value['unicode']?> >
                            &#<?php echo $value['unicode']?>
                        </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div id="sym_warning" class="text-danger"></div>
                    
                <canvas id="canvas" width="300" height="300" class="canvas"></canvas>
                <div class="icon-container">
                    <div onclick="clearCanvas()">
                        <i class="fas fa-sync text-primary"></i>
                        <div>Clear</div>
                        <!-- ✘ -->
                    </div>
                    <div onclick="submitImage()">
                        <i class="fas fa-check text-success"></i>
                        <div>Submit</div>
                        <!-- ✔ -->
                    </div>
                    <div onclick="nextChar()">
                        <i class="fas fa-ban text-danger"></i>
                        <div>Skip</div>
                    </div>
                </div>
                <button id="freedraw" class="btn btn-info">Pause freedraw</button>
            </div>
        </div>

        <div id="snackbar"></div>

    </body>
    <script>
        let canvas;
        window.onload =  function () {
            $("#charSelect option:first").attr('selected',true);
            canvas = window._canvas = new fabric.Canvas('canvas');
            canvas.freeDrawingBrush.width = 8;
            canvas.isDrawingMode = true;
            canvas.freeDrawingBrush.color = '#000000';
            canvas.renderAll();
            var pause_btn = document.getElementById('freedraw');
            pause_btn.addEventListener('click', function () {
                canvas.isDrawingMode = !canvas.isDrawingMode;
                if(canvas.isDrawingMode) {
                    pause_btn.innerHTML = "Pause freedraw";
                }
                else {
                    pause_btn.innerHTML = "Enable freedraw";
                }
            });
            $('#charSelect').on('change', function() {
                sym_warning(this.value);
            });
        };
        function sym_warning(num) {
            if( num > 3389 && num < 3416 )
                $('#sym_warning').text("Don't trace the dotted lines");
            else
                $('#sym_warning').text(" ");
        }
        function submitImage() {
            let char = document.getElementById('charSelect').value;
            let img = canvas.toDataURL('png');
            showSnackbar('Uploading '+ String.fromCharCode(char));
            $.post('dataentry',{
                'image':img,
                'char':char
            },function (data,status) {
                if(status === 'success') {
                    showSnackbar('Uploaded '+ String.fromCharCode(data));
                    if(data!='3415')  
                        nextChar();
                    if(data == '3415')
                        setTimeout(()=>{
                            showSnackbar('Thank you for your time');
                        }, 1000);
                }
            });
        }
        function clearCanvas() {
            canvas.clear();
        }
        function nextChar() {
            canvas.clear();
            $('#charSelect > option:selected')
                .prop('selected',false)
                .next()
                .prop('selected',true);
            sym_warning( $('#charSelect').val() );
            setTimeout(() => {
                showSnackbar('Current character '+ String.fromCharCode($('#charSelect').val()));
            }, 3000);
        }
        function showSnackbar(text) {
            let x = document.getElementById("snackbar");
            x.innerText = text;
            x.className = "show";
            setTimeout(function(){ x.className = x.className.replace("show", ""); }, 3000);
        }
    </script>
</html>
